In [ ]:
import torch
import numpy as np

data = torch.load("data/nasbench101/all_nasbench101.pt")  # 按你的路径替换
# data = torch.load("data/nasbench201/all_nasbench201.pt")

def is_undirected(adj):
    a = np.asarray(adj)
    return np.array_equal(a, a.T)

undirected = 0
directed = 0
first_directed = None

for k, v in data.items():
    adj = v["adj"]
    if is_undirected(adj):
        undirected += 1
    else:
        directed += 1
        if first_directed is None:
            first_directed = (k, np.sum(np.asarray(adj) != np.asarray(adj).T))

print("undirected:", undirected, "directed:", directed)
print("first_directed:", first_directed)

/tmp/ipykernel_138858/3529554614.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load("data/nasbench101/all_nasbench101.pt")  # 按你的路径替换


undirected: 0 directed: 423624
first_directed: (0, 18)


In [ ]:
import torch
import numpy as np
from nnformer.data_process.nasbench.dataset import NasbenchDataset

dataset = NasbenchDataset(
    logger=type("L", (), {"info": print})(),
    dataset="nasbench101",
    part="train",
    data_path="data/nasbench101/all_nasbench101.pt",
    percent=100,
    lbd_consistency=0,
)
sample = dataset[0]
adj = sample["code_adj"].cpu().numpy()
print("code_adj_undirected:", np.array_equal(adj, adj.T))

Building dataset train from .pth file
Loading cached data from ./data/nasbench101/nasbench101_0/train_100_cached_data.pth
Finish Loading dataset train; Number of samples: 100; Time: 0.00s
code_adj_undirected: False


/home/rtx4090/code/python/current/GraphRegression/nnformer/data_process/nasbench/dataset.py:51: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(cache_file)


In [ ]:
from nnformer.data_process.fixed_length_sampler import FixedLengthBatchSampler
from torch.utils.data import DataLoader  # 正确导入 PyTorch 的 DataLoader

trainset = NasbenchDataset(
    logger=type("L", (), {"info": print})(),
    dataset="nasbench101",
    part="train",
    data_path="data/nasbench101/all_nasbench101.pt",
    percent=100,
    lbd_consistency=0,
)
train_sampler = FixedLengthBatchSampler(
    trainset, "nasbench101", 32, include_partial=True
)
train_loader = DataLoader(
    trainset,
    shuffle=(train_sampler is None),
    num_workers=1,
    pin_memory=True,
    persistent_workers=True,
    batch_sampler=train_sampler,
)

Building dataset train from .pth file
Loading cached data from ./data/nasbench101/nasbench101_0/train_100_cached_data.pth
Finish Loading dataset train; Number of samples: 100; Time: 0.00s


In [ ]:
for batch in train_loader:
    print(len(batch))
    break  # 仅打印第一个batch，避免输出过多

8


In [3]:
import faiss
import numpy as np

# 生成随机数据
d = 128  # 向量维度
nb = 10000  # 数据库大小
nq = 5  # 查询向量数量
xb = np.random.random((nb, d)).astype('float32')
xq = np.random.random((nq, d)).astype('float32')

# 构建索引：使用IVFFlat索引
nlist = 100  # 聚类中心数量
quantizer = faiss.IndexFlatL2(d)  # 使用L2距离的量化器
index = faiss.IndexIVFFlat(quantizer, d, nlist)

index.train(xb)
index.add(xb)
print("索引中向量数量:", index.ntotal)

# 执行ANN搜索
k = 4  # 返回最近邻数量
D, I = index.search(xq, k)  # D为距离，I为索引
print("最近邻索引:\n", I)
print("对应距离:\n", D)


索引中向量数量: 10000
最近邻索引:
 [[7590 4577  253 8470]
 [1129 1816 6683  350]
 [3135 6163 3409 2583]
 [9319 6188 9188  239]
 [ 279 6521 7781 4248]]
对应距离:
 [[14.558121 15.061212 15.365236 16.76867 ]
 [15.434195 15.623983 15.667612 15.689288]
 [15.7552   17.202202 17.215492 17.226364]
 [15.816597 16.006453 16.994236 17.000565]
 [14.795727 15.676227 15.934057 16.31137 ]]


In [ ]:
import time
import numpy as np
import faiss


np.random.seed(123)
d = 128
nb = 50000
nq = 100
k = 10
xb = np.random.random((nb, d)).astype('float32')
xq = np.random.random((nq, d)).astype('float32')

flat_l2 = faiss.IndexFlatL2(d)
flat_l2.add(xb)
t0 = time.perf_counter()
D0, I0 = flat_l2.search(xq, k)
base_time = time.perf_counter() - t0
results = []

def recall_at_k(I_ref, I_pred):
    inter = 0
    for i in range(I_ref.shape[0]):
        inter += len(set(I_ref[i]).intersection(set(I_pred[i])))
    return inter / (I_ref.shape[0] * I_ref.shape[1])

def bench_search(index, name):
    t1 = time.perf_counter()
    D, I = index.search(xq, k)
    t_search = time.perf_counter() - t1
    rec = recall_at_k(I0, I)
    results.append((name, t_search, rec))

idx = faiss.IndexFlatL2(d)
idx.add(xb)
bench_search(idx, "FlatL2")

idx_ip = faiss.IndexFlatIP(d)
idx_ip.add(xb)
t1 = time.perf_counter()
D_ip, I_ip = idx_ip.search(xq, k)
t_ip = time.perf_counter() - t1
results.append(("FlatIP", t_ip, None))

nlist = 256
quant = faiss.IndexFlatL2(d)
ivf_flat = faiss.IndexIVFFlat(quant, d, nlist)
ivf_flat.train(xb)
ivf_flat.add(xb)
for npv in [1, 5, 10, 20]:
    ivf_flat.nprobe = npv
    bench_search(ivf_flat, f"IVFFlat(nprobe={npv})")

ivf_pq = faiss.IndexIVFPQ(faiss.IndexFlatL2(d), d, nlist, 16, 8)
ivf_pq.train(xb)
ivf_pq.add(xb)
for npv in [5, 10, 20, 40]:
    ivf_pq.nprobe = npv
    bench_search(ivf_pq, f"IVFPQ(m=16,8bit,nprobe={npv})")

ivf_sq8 = faiss.IndexIVFScalarQuantizer(faiss.IndexFlatL2(d), d, nlist, faiss.ScalarQuantizer.QT_8bit)
ivf_sq8.train(xb)
ivf_sq8.add(xb)
for npv in [5, 10, 20, 40]:
    ivf_sq8.nprobe = npv
    bench_search(ivf_sq8, f"IVF-SQ8(nprobe={npv})")

hnsw = faiss.IndexHNSWFlat(d, 32)
hnsw.add(xb)
for ef in [16, 32, 64, 128]:
    hnsw.hnsw.efSearch = ef
    bench_search(hnsw, f"HNSWFlat(M=32,efSearch={ef})")

lsh = faiss.IndexLSH(d, 64)
lsh.add(xb)
t1 = time.perf_counter()
D_lsh, I_lsh = lsh.search(xq, k)
t_lsh = time.perf_counter() - t1
try:
    rec_lsh = recall_at_k(I0, I_lsh)
except:
    rec_lsh = None
results.append(("LSH(64bits)", t_lsh, rec_lsh))

pq = faiss.IndexPQ(d, 16, 8)
pq.train(xb)
pq.add(xb)
bench_search(pq, "PQ(m=16,8bit)")

print("Baseline FlatL2 search time:", round(base_time, 6), "s")
for name, t, rec in results:
    print(name, "time:", round(t, 6), "s", "recall:", ("{:.4f}".format(rec) if rec is not None else "-"))


Baseline FlatL2 search time: 0.030797 s
FlatL2 time: 0.049697 s recall: 1.0000
FlatIP time: 0.030003 s recall: -
IVFFlat(nprobe=1) time: 0.007873 s recall: 0.0420
IVFFlat(nprobe=5) time: 0.007783 s recall: 0.1340
IVFFlat(nprobe=10) time: 0.007763 s recall: 0.1960
IVFFlat(nprobe=20) time: 0.007752 s recall: 0.2960
IVFPQ(m=16,8bit,nprobe=5) time: 0.007087 s recall: 0.1020
IVFPQ(m=16,8bit,nprobe=10) time: 0.007699 s recall: 0.1280
IVFPQ(m=16,8bit,nprobe=20) time: 0.008575 s recall: 0.1560
IVFPQ(m=16,8bit,nprobe=40) time: 0.008259 s recall: 0.1910
IVF-SQ8(nprobe=5) time: 0.008067 s recall: 0.1340
IVF-SQ8(nprobe=10) time: 0.007629 s recall: 0.1960
IVF-SQ8(nprobe=20) time: 0.011683 s recall: 0.2960
IVF-SQ8(nprobe=40) time: 0.004912 s recall: 0.4640
HNSWFlat(M=32,efSearch=16) time: 0.000293 s recall: 0.2960
HNSWFlat(M=32,efSearch=32) time: 0.000408 s recall: 0.4430
HNSWFlat(M=32,efSearch=64) time: 0.000609 s recall: 0.5970
HNSWFlat(M=32,efSearch=128) time: 0.00112 s recall: 0.7650
LSH(64bits)